
const PackageItem = [
    {
        title: "@grpc/grpc-js",
        version: "1.11.1",
        licenseApiUrl: "https://api.github.com/repos/grpc/grpc-node/license",
        repositoryUrl: "https://github.com/grpc/grpc-node",
    },
    {
        title: "@grpc/proto-loader",
        version: "0.7.13",
        licenseApiUrl: "https://api.github.com/repos/grpc/grpc-node/license",
        repositoryUrl: "https://github.com/grpc/grpc-node",
    },
    {
        title: "bcryptjs",
        version: "2.4.3",
        licenseApiUrl: "https://api.github.com/repos/dcodeIO/bcrypt.js/license",
        repositoryUrl: "https://github.com/dcodeIO/bcrypt.js",
    },
    {
        title: "crypto",
        version: "1.0.1",
        licenseApiUrl: "https://api.github.com/repos/npm/deprecate-holder/license",
        repositoryUrl: "https://github.com/npm/deprecate-holder",
    },
    {
        title: "express",
        version: "4.18.2",
        licenseApiUrl: "https://api.github.com/repos/expressjs/express/license",
        repositoryUrl: "https://github.com/expressjs/express",
    },
    {
        title: "express-rate-limit",
        version: "7.1.5",
        licenseApiUrl: "https://api.github.com/repos/express-rate-limit/express-rate-limit/license",
        repositoryUrl: "https://github.com/express-rate-limit/express-rate-limit",
    },
    {
        title: "express-slow-down",
        version: "2.0.1",
        licenseApiUrl: "https://api.github.com/repos/express-rate-limit/express-slow-down/license",
        repositoryUrl: "https://github.com/express-rate-limit/express-slow-down",
    },
    {
        title: "helmet",
        version: "8.0.0",
        licenseApiUrl: "https://api.github.com/repos/helmetjs/helmet/license",
        repositoryUrl: "https://github.com/helmetjs/helmet",
    },
    {
        title: "jsonwebtoken",
        version: "9.0.2",
        licenseApiUrl: "https://api.github.com/repos/auth0/node-jsonwebtoken/license",
        repositoryUrl: "https://github.com/auth0/node-jsonwebtoken",
    },
    {
        title: "modbus-serial",
        version: "8.0.9",
        licenseApiUrl: "https://api.github.com/repos/yaacov/node-modbus-serial/license",
        repositoryUrl: "https://github.com/yaacov/node-modbus-serial",
    },
    {
        title: "mongoose",
        version: "5.13.14",
        licenseApiUrl: "https://api.github.com/repos/Automattic/mongoose/license",
        repositoryUrl: "https://github.com/Automattic/mongoose",
    },
    {
        title: "passport",
        version: "0.6.0",
        licenseApiUrl: "https://api.github.com/repos/jaredhanson/passport/license",
        repositoryUrl: "https://github.com/jaredhanson/passport",
    },
    {
        title: "passport-jwt",
        version: "4.0.1",
        licenseApiUrl: "https://api.github.com/repos/mikenicholson/passport-jwt/license",
        repositoryUrl: "https://github.com/mikenicholson/passport-jwt",
    },
    {
        title: "serialport",
        version: "12.0.0",
        licenseApiUrl: "https://api.github.com/repos/serialport/node-serialport/license",
        repositoryUrl: "https://github.com/serialport/node-serialport",
    },
    {
        title: "socket.io",
        version: "4.6.2",
        licenseApiUrl: "https://api.github.com/repos/socketio/socket.io/license",
        repositoryUrl: "https://github.com/socketio/socket.io",
    },
    {
        title: "stream-throttle",
        version: "0.1.3",
        licenseApiUrl: "https://api.github.com/repos/tjgq/node-stream-throttle/license",
        repositoryUrl: "https://github.com/tjgq/node-stream-throttle",
    },
    {
        title: "@azure/msal-browser",
        version: "3.17.0",
        licenseApiUrl: "https://api.github.com/repos/AzureAD/microsoft-authentication-library-for-js/license",
        repositoryUrl: "https://github.com/AzureAD/microsoft-authentication-library-for-js",
    },
    {
        title: "@azure/msal-react",
        version: "2.0.19",
        licenseApiUrl: "https://api.github.com/repos/AzureAD/microsoft-authentication-library-for-js/license",
        repositoryUrl: "https://github.com/AzureAD/microsoft-authentication-library-for-js",
    },
    {
        title: "@emotion/react",
        version: "11.11.0",
        licenseApiUrl: "https://api.github.com/repos/emotion-js/emotion/license",
        repositoryUrl: "https://github.com/emotion-js/emotion",
    },
    {
        title: "@emotion/styled",
        version: "11.11.0",
        licenseApiUrl: "https://api.github.com/repos/emotion-js/emotion/license",
        repositoryUrl: "https://github.com/emotion-js/emotion",
    },
    {
        title: "@fontsource/roboto",
        version: "5.0.2",
        licenseApiUrl: "https://api.github.com/repos/fontsource/font-files/license",
        repositoryUrl: "https://github.com/fontsource/font-files",
    },
    {
        title: "@mui/icons-material",
        version: "5.11.16",
        licenseApiUrl: "https://api.github.com/repos/mui/material-ui/license",
        repositoryUrl: "https://github.com/mui/material-ui",
    },
    {
        title: "@mui/material",
        version: "5.13.4",
        licenseApiUrl: "https://api.github.com/repos/mui/material-ui/license",
        repositoryUrl: "https://github.com/mui/material-ui",
    },
    {
        title: "@mui/x-data-grid",
        version: "6.16.0",
        licenseApiUrl: "https://api.github.com/repos/mui/mui-x/license",
        repositoryUrl: "https://github.com/mui/mui-x",
    },
    {
        title: "@mui/x-data-grid-generator",
        version: "6.19.2",
        licenseApiUrl: "https://api.github.com/repos/mui/mui-x/license",
        repositoryUrl: "https://github.com/mui/mui-x",
    },
    {
        title: "@mui/x-date-pickers",
        version: "5.0.15",
        licenseApiUrl: "https://api.github.com/repos/mui/mui-x/license",
        repositoryUrl: "https://github.com/mui/mui-x",
    },
    {
        title: "canvas-gauges",
        version: "2.1.7",
        licenseApiUrl: "https://api.github.com/repos/Mikhus/canvas-gauges/license",
        repositoryUrl: "https://github.com/Mikhus/canvas-gauges",
    },
    {
        title: "dayjs",
        version: "1.11.9",
        licenseApiUrl: "https://api.github.com/repos/iamkun/dayjs/license",
        repositoryUrl: "https://github.com/iamkun/dayjs",
    },
    {
        title: "echarts-for-react",
        version: "3.0.2",
        licenseApiUrl: "https://api.github.com/repos/hustcc/echarts-for-react/license",
        repositoryUrl: "https://github.com/hustcc/echarts-for-react",
    },
    {
        title: "file-saver",
        version: "2.0.5",
        licenseApiUrl: "https://api.github.com/repos/eligrey/FileSaver.js/license",
        repositoryUrl: "https://github.com/eligrey/FileSaver.js",
    },
    {
        title: "intl",
        version: "1.2.5",
        licenseApiUrl: "https://api.github.com/repos/andyearnshaw/Intl.js/license",
        repositoryUrl: "https://github.com/andyearnshaw/Intl.js",
    },
    {
        title: "jwt-decode",
        version: "3.1.2",
        licenseApiUrl: "https://api.github.com/repos/auth0/jwt-decode/license",
        repositoryUrl: "https://github.com/auth0/jwt-decode",
    },
    {
        title: "leaflet",
        version: "1.9.4",
        licenseApiUrl: "https://api.github.com/repos/Leaflet/Leaflet/license",
        repositoryUrl: "https://github.com/Leaflet/Leaflet",
    },
    {
        title: "lp-react-virtualized-auto-sizer-react-18",
        version: "1.0.7",
        licenseApiUrl: "https://api.github.com/repos/bvaughn/react-virtualized-auto-sizer/license",
        repositoryUrl: "https://github.com/bvaughn/react-virtualized-auto-sizer",
    },
    {
        title: "moment",
        version: "2.29.4",
        licenseApiUrl: "https://api.github.com/repos/moment/moment/license",
        repositoryUrl: "https://github.com/moment/moment",
    },
    {
        title: "notistack",
        version: "3.0.1",
        licenseApiUrl: "https://api.github.com/repos/iamhosseindhv/notistack/license",
        repositoryUrl: "https://github.com/iamhosseindhv/notistack",
    },
    {
        title: "react",
        version: "18.2.0",
        licenseApiUrl: "https://api.github.com/repos/facebook/react/license",
        repositoryUrl: "https://github.com/facebook/react",
    },
    {
        title: "react-colorful",
        version: "5.6.1",
        licenseApiUrl: "https://api.github.com/repos/omgovich/react-colorful/license",
        repositoryUrl: "https://github.com/omgovich/react-colorful",
    },
    {
        title: "react-contexify",
        version: "6.0.0",
        licenseApiUrl: "https://api.github.com/repos/fkhadra/react-contexify/license",
        repositoryUrl: "https://github.com/fkhadra/react-contexify",
    },
    {
        title: "react-custom-scrollbars-2",
        version: "4.5.0",
        licenseApiUrl: "https://api.github.com/repos/RobPethick/react-custom-scrollbars-2/license",
        repositoryUrl: "https://github.com/RobPethick/react-custom-scrollbars-2",
    },
    {
        title: "react-dom",
        version: "18.2.0",
        licenseApiUrl: "https://api.github.com/repos/facebook/react/license",
        repositoryUrl: "https://github.com/facebook/react",
    },
    {
        title: "react-easy-crop",
        version: "4.7.4",
        licenseApiUrl: "https://api.github.com/repos/ValentinH/react-easy-crop/license",
        repositoryUrl: "https://github.com/ValentinH/react-easy-crop",
    },
    {
        title: "react-gauge-component",
        version: "1.2.21",
        licenseApiUrl: "https://api.github.com/repos/antoniolago/react-gauge-component/license",
        repositoryUrl: "https://github.com/antoniolago/react-gauge-component",
    },
    {
        title: "react-intl",
        version: "6.4.3",
        licenseApiUrl: "https://api.github.com/repos/formatjs/formatjs/license",
        repositoryUrl: "https://github.com/formatjs/formatjs",
    },
    {
        title: "react-ios-pwa-prompt",
        version: "1.8.4",
        licenseApiUrl: "https://api.github.com/repos/chrisdancee/react-ios-pwa-prompt/license",
        repositoryUrl: "https://github.com/chrisdancee/react-ios-pwa-prompt",
    },
    {
        title: "react-leaflet",
        version: "4.2.1",
        licenseApiUrl: "https://api.github.com/repos/PaulLeCam/react-leaflet/license",
        repositoryUrl: "https://github.com/PaulLeCam/react-leaflet",
    },
    {
        title: "react-leaflet-cluster",
        version: "2.1.0",
        licenseApiUrl: "https://api.github.com/repos/akursat/react-leaflet-cluster/license",
        repositoryUrl: "https://github.com/akursat/react-leaflet-cluster",
    },
    {
        title: "react-markdown",
        version: "8.0.7",
        licenseApiUrl: "https://api.github.com/repos/remarkjs/react-markdown/license",
        repositoryUrl: "https://github.com/remarkjs/react-markdown",
    },
    {
        title: "react-rnd",
        version: "10.4.10",
        licenseApiUrl: "https://api.github.com/repos/bokuweb/react-rnd/license",
        repositoryUrl: "https://github.com/bokuweb/react-rnd",
    },
    {
        title: "react-router-dom",
        version: "6.8.0",
        licenseApiUrl: "https://api.github.com/repos/remix-run/react-router/license",
        repositoryUrl: "https://github.com/remix-run/react-router",
    },
    {
        title: "react-scripts",
        version: "5.0.1",
        licenseApiUrl: "https://api.github.com/repos/facebook/create-react-app/license",
        repositoryUrl: "https://github.com/facebook/create-react-app",
    },
    {
        title: "react-window",
        version: "1.8.9",
        licenseApiUrl: "https://api.github.com/repos/bvaughn/react-window/license",
        repositoryUrl: "https://github.com/bvaughn/react-window",
    },
    {
        title: "socket.io-client",
        version: "4.6.2",
        licenseApiUrl: "https://api.github.com/repos/socketio/socket.io/license",
        repositoryUrl: "https://github.com/socketio/socket.io",
    },
    {
        title: "sortablejs",
        version: "1.15.2",
        licenseApiUrl: "https://api.github.com/repos/SortableJS/Sortable/license",
        repositoryUrl: "https://github.com/SortableJS/Sortable",
    },
    {
        title: "xlsx",
        version: "0.18.5",
        licenseApiUrl: "https://api.github.com/repos/SheetJS/sheetjs/license",
        repositoryUrl: "https://github.com/SheetJS/sheetjs",
    },
]

export default PackageItem